FROM ubuntu:16.04

RUN apt-get update

RUN apt-get install -y \
  gobject-introspection \
  gstreamer-1.0 \
  gstreamer1.0-libav \
  gstreamer1.0-tools \
  libasound2-dev \
  libcairo2-dev \
  libgif-dev \
  libgirepository1.0-dev \
  libgstreamer-plugins-base1.0-dev \
  libpango1.0-dev \
  libsndfile1-dev \
  pkg-config \
  poppler-utils \
  python \
  python3-gi \
  python3-gi-cairo \
  python-dev \
  python-gi \
  python-gi-cairo \
  python-gst-1.0 \
  python-imaging \
  python-pip \
  python-virtualenv

RUN pip install tox
