#!/bin/bash

# GNU MediaGoblin -- federated, autonomous media hosting
# Copyright (C) 2018 MediaGoblin contributors.  See AUTHORS.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Exit on first failing command.
set -e
# Echo commands to console.
set -x

IMAGE_NAME="mediagoblin-image"
CONTAINER_NAME="mediagoblin"

docker version

# Delete pyc files from previous builds.
find . -name "*.pyc" -delete

docker build \
  --tag "$IMAGE_NAME" \
  --file Dockerfile.test \
  .

# Clear any previous container.
docker rm -f "$CONTAINER_NAME" &> /dev/null || true

docker run \
  --tty \
  --detach \
  --volume "${PWD}:/app" \
  --volume "tox-ephemeral:/app/.tox" \
  --workdir "/app" \
  --name "$CONTAINER_NAME" \
  "$IMAGE_NAME"
