# GNU MediaGoblin -- federated, autonomous media hosting
# Copyright (C) 2018 MediaGoblin contributors.  See AUTHORS.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

FROM ubuntu:16.04

RUN apt-get update

RUN apt-get install -y \
  libcairo2-dev \
  libgirepository1.0-dev \
  libgstreamer-plugins-base1.0-dev \
  pkg-config \
  python \
  python3-gi \
  python-dev \
  python-gi \
  python-pip \
  python-virtualenv

RUN pip install tox
