#!/bin/bash

# Exit on first failing command.
set -e
# Echo commands to console.
set -x

IMAGE_NAME="mediagoblin-image"
CONTAINER_NAME="mediagoblin"

docker version

# Delete pyc files from previous builds.
find . -name "*.pyc" -delete

docker build \
  --tag "$IMAGE_NAME" \
  --file Dockerfile.test \
  .

# Clear any previous container.
docker rm -f "$CONTAINER_NAME" &> /dev/null || true

docker run \
  --tty \
  --detach \
  --volume "${PWD}:/app" \
  --volume "tox-ephemeral:/app/.tox" \
  --workdir "/app" \
  --name "$CONTAINER_NAME" \
  "$IMAGE_NAME"
