#!/bin/bash

# GNU MediaGoblin -- federated, autonomous media hosting
# Copyright (C) 2019 MediaGoblin contributors.  See AUTHORS.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Exit on first failing command.
set -e
# Echo commands to console.
set -x

docker version
docker-compose version

mkdir \
  --parents \
  --mode 777 \
  user_dev/media \
  user_dev/crypto

docker-compose up --build -d

# Give the container time to start up.
sleep 10

# Verify that MediaGoblin responds to HTTP requests on the given port.
curl \
  --retry 15 \
  --retry-delay 2 \
  --fail \
  "http://localhost:6543/" > /dev/null
